// <auto-generated />
namespace EmpleadosCargos.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CambiosenlanulabilidaddeCargo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambiosenlanulabilidaddeCargo));
        
        string IMigrationMetadata.Id
        {
            get { return "201603040354158_Cambios en la nulabilidad de Cargo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
